server:
  port: 8080

spring:
  application:
    name: 30days-learning
  datasource:
    url: jdbc:mysql://localhost:3306/studySchema?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: localhost # 你的Redis地址
    port: 6379
    password: # 无密码则留空
    lettuce:
      pool:
        max-active: 8 # 最大连接数
        max-idle: 8   # 最大空闲连接
        min-idle: 0   # 最小空闲连接
    timeout: 1000ms # 超时时间

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.example: debug